### ISSUE TITLE
formatRecursiveType function clashes with Array prototype updates

### ISSUE THREAD

**Issue by jmenashe** [awslabs/dynamodb-document-js-sdk#10]
The function "formatRecursiveType" in datatypes.js has the following snippet:

    for (var key in dataType) {
      value[key] = this.formatDataType(dataType[key]);
    }

Methods that are added to the array prototype come out in this loop. You should use an index-based for loop for arrays:

    for(var i = 0; i < dataType.length; i++) {
      value[dataType[i]] = this.formatDataType(dataType[i]);
    }

Edit: It probably would make sense to do an analogous modification for Object as well.

**Comment by raymolin** [comment]
taken care of here 9253ce4976d41b0ac7586e1c068e9996e120744c
