### ISSUE TITLE
One or more parameter values were invalid: An AttributeValue may not contain an empty string

### ISSUE THREAD

**Issue by whyvez** [awslabs/dynamodb-document-js-sdk#18]
Should empty string value be converted to NULL? Would help not having to walk doc for an empty string value before saving.

**Comment by bhavik-obl** [comment]
you check whether the passed value is null or not then pass non null values only..

**Comment by raymolin** [comment]
I think for the sake of use cases where users decide to store empty strings in DynamoDB, we probably don't want to default converting empty strings to NULL values.  I would agree with doing checks before entering an AttributeValue.
