### ISSUE TITLE
Does not work with Elastic Beanstalk

### ISSUE THREAD

**Issue by rickwaugh1** [awslabs/dynamodb-document-js-sdk#19]
So, I have written an app using this, that we need to deploy. I had added it to my package.json file as follows:

"dynamodb-document-js-sdk":"git://github.com/awslabs/dynamodb-document-js-sdk",

This works fine when simply running this in node standalone. But I tried to set up my application in Beanstalk, and I'm now finding it doesn't work.  This is what I get in the npm debug log from beanstalk. I'm pretty much screwed right now if this is so.

317 silly lockFile 1b4d9892-awslabs-dynamodb-document-js-sdk git://github.com/awslabs/dynamodb-document-js-sdk
318 silly lockFile 1b4d9892-awslabs-dynamodb-document-js-sdk git://github.com/awslabs/dynamodb-document-js-sdk
319 error not found: git
320 error Failed using git.
320 error This is most likely not a problem with npm itself.
320 error Please check if you have git installed and in your PATH.
321 error System Linux 3.14.20-20.44.amzn1.x86_64
322 error command "/opt/elasticbeanstalk/node-install/node-v0.10.21-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v0.10.21-linux-x64/bin/npm" "--production" "install"
323 error cwd /tmp/deployment/application
324 error node -v v0.10.21
325 error npm -v 1.4.4
326 error code ENOGIT

**Comment by realchaseadams** [comment]
Is there a reason this isn't published to npm?
