### ISSUE TITLE
TypeError when using attribute updates and DELETE action

### ISSUE THREAD

**Issue by garthomite** [awslabs/dynamodb-document-js-sdk#20]
When using the DELETE action on AttributeValueUpdate you can omit the Value, however the formatter will die here trying to format a value that doesn't exist.

    TypeError: Cannot read property 'datatype' of undefined
        at isSetType (dynamodb-doc/lib/datatypes.js:28:24)
        at DynamoDBDatatype.formatDataType (dynamodb-doc/lib/datatypes.js:110:20)
        at formatUpdates (dynamodb-doc/lib/formatter.js:60:43)

Trying to use any value will give you this error on strings or numbers:

DELETE action with value is not supported for the type STRING

Workaround for me was to patch formatter.js:54 to:

            if (updates.hasOwnProperty(attr)) {
                var actionValue = {};
                var action = updates[attr].Action;
    
                actionValue.Action = action;
                if (updates[attr].hasOwnProperty('Value')){
                    var value = updates[attr].Value;
                    actionValue.Value = t.formatDataType(value);
                }
                attrUpdates[attr] = actionValue;
            }

After that DELETE updates work fine

**Comment by benweet** [comment]
+1
Thanks for the workaround.

**Comment by raymolin** [comment]
Thanks guys, pushed fix + test

**Comment by SamVerschueren** [comment]
Can this fix be pushed to npm please?
