### ISSUE TITLE
BatchWriteItem missing?

### ISSUE THREAD

**Issue by danielgollas** [awslabs/dynamodb-document-js-sdk#22]
There seems to be no method for BatchWriteItem, is this expected to be available soon or is there a workaround? I figure maybe I can create a clasic params object using regular js objects and then use it with the original dynamodb sdk where BatchWriteItem is present. 

Thanks!

**Comment by raymolin** [comment]
The document SDK is a library that wraps around the aws SDK.  You are able to access the BatchWriteItem API using the "batchWriteItem" method.
