### ISSUE TITLE
Network Errors Being Reported Incorrectly?

### ISSUE THREAD

**Issue by rickwaugh1** [awslabs/dynamodb-document-js-sdk#27]
I have now twice run into problems using this library, once during load testing, once in production with a very lightly used app, where it reports that the dynamo end point is not found, and the service may not be available in that region.

Is this a spurious error? I find it hard to believe that I can't get at Dynamo from an EC2 instance running in the same region. There were no errors reported from Dynamo, no throttled requests, no reports of having gone over capacity. So, I'm at a loss to explain why the following would turn up. The message comes from an event listener set up in the event_listeners.js file, in the lib directory.

{"level":"error","message":"{\"message\":\"Inaccessible host: `dynamodb.us-west-2.amazonaws.com'. This service may not be available in the `us-west-2' region.\",\"stack\":\"UnknownEndpoint: Inaccessible host: `dynamodb.us-west-2.amazonaws.com'. This service may not be available in the `us-west-2' region.\\n    at Request.ENOTFOUND_ERROR (/var/app/current/node_modules/aws-sdk/lib/event_listeners.js:355:46)\\n at Request.callListeners (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:100:18)\\n at Request.emit (/var/app/current/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n at Request.emit (/var/app/current/node_modules/aws-sdk/lib/request.js:604:14)\\n at ClientRequest.error (/var/app/current/node_modules/aws-sdk/lib/event_listeners.js:204:22)\\n at ClientRequest.<anonymous> (/var/app/current/node_modules/aws-sdk/lib/http/node.js:61:19)\\n at ClientRequest.EventEmitter.emit (events.js:117:20)\\n    at CleartextStream.socketErrorListener (http.js:1547:9)\\n    at CleartextStream.EventEmitter.emit (events.js:95:17)\\n    at Socket.onerror (tls.js:1431:17)\"}","timestamp":"2015-03-20T14:42:54.403Z"}

**Comment by raymolin** [comment]
From what it looks like, this error stems from a networking issue.  Can you verify that the EC2 node is getting traffic properly?

**Comment by rickwaugh1** [comment]
Two separate applications, different servers. Most of the time, 
functioning properly. Then get intermittent messages. One was being load 
tested, so conceivably, could have nuked the network. Other one, it's a 
small, single server application, that works fine. Except for twice this 
morning.

I have a ticket in with AWS on the application. But I'm confused as to 
why it would start then stop doing this.

On 2015-03-20 2:15 PM, raymolin wrote:
>
> From what it looks like, this error stems from a networking issue. Can 
> you verify that the EC2 node is getting traffic properly?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/awslabs/dynamodb-document-js-sdk/issues/27#issuecomment-84149738>.
>

-- 
Server Developer
Finger Food Studios Inc.
tel: 604-475-0350
email: rick@fingerfoodstudios.com

skype: rick.waugh4

www.fingerfoodstudios.com

MESSAGES / COMMENTS This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately and return the original message to us at the above address. Thank you.

**Comment by rickwaugh1** [comment]
AWS support has confirmed that the latest errors did indeed come from a 
problem with Dynamo during the times we saw the error.

On 2015-03-20 2:15 PM, raymolin wrote:
>
> From what it looks like, this error stems from a networking issue. Can 
> you verify that the EC2 node is getting traffic properly?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/awslabs/dynamodb-document-js-sdk/issues/27#issuecomment-84149738>.
>

-- 
Server Developer
Finger Food Studios Inc.
tel: 604-475-0350
email: rick@fingerfoodstudios.com

skype: rick.waugh4

www.fingerfoodstudios.com

MESSAGES / COMMENTS This message is intended for the use of the individual or entity to which it is addressed and may contain information that is privileged, confidential and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately and return the original message to us at the above address. Thank you.

**Comment by raymolin** [comment]
It seems there may have been some network issues last Friday (3/20).  Are you continuing to see issues still?

**Comment by rickwaugh1** [comment]
No it has looked good since. That being said, this is a pretty low traffic
site.

**Comment by raymolin** [comment]
There can be various reasons for networking issues.  That being said, the library is layered on top of the aws-js-sdk, which actually does error handling, so this isn't an issue for the document level sdk.  Also, it seems like it was a server side issue, but glad to see it's working!
