### ISSUE TITLE
Please update package.json

### ISSUE THREAD

**Issue by calexbu** [awslabs/dynamodb-document-js-sdk#28]
Guys, big request!

Please keep updated package.json file (especially "version" section) after merging or fixing bugs.

NPM still use old version (before last merging).

**Comment by lsegal** [comment]
@calexbu an npm package is different and distinct from a Git repository. Merging or committing to the master branch should not constitute a new version of the package until an actual release is created. It looks like the npm package is still on 1.0.0 from the release in February, which doesn't include the last 3 commit/merges to this repository. If a new npm package is released, it would include these updates and a new version.

**Comment by calexbu** [comment]
Thanks for good explanation.
