### ISSUE TITLE
usage corrupts existing DynamoDB client

### ISSUE THREAD

**Issue by doapp-ryanp** [awslabs/dynamodb-document-js-sdk#29]
I want to have a handle to the original DynamoDB client for node.js as well as a handle to the dynamodb-doc client.  Reason being, for some of my code I don't want the dynamodb-doc code getting involved. 

I figured I could just have the `new AWS.DynamoDB()` and `new DOC.DynamoDB()` co-exist as 2 different vars, but that is not the case. As soon as I `new DOC.DynamoDB(existingDynamoDbClient)` it corrupts the `existingDynamoDbClient`.

Here is a simple test case that shows what I am talking about.  FWIW I'm using io.js 1.8.1 (happens on other versions of node though) and DynamoDb local via `java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -port 8000 -sharedDb -inMemory`

If you un-comment the `var docClient...` line below, you will see how the doc client corrupts the existing DynamoDb client even though I'm not using the doc client anywhere.  As you can see I turned on the AWS SDK logger, so you can see the doc client is (incorrectly) serializing the object into Dyanamo data Model notation.

```javascript
var AWS = require('aws-sdk'),
    DOC = require("dynamodb-doc");

AWS.config.update({logger: process.stdout});

var dbClient = new AWS.DynamoDB({endpoint: new AWS.Endpoint("http://localhost:8000")}),
    tableName = 'ws-access-tokens',
    expires = new Date();

//Uncomment line below to expose bug. Object gets double serialized even though I'm not using docClient
//var docClient = new DOC.DynamoDB(dbClient);

var ctParams = {
  TableName: tableName,
  KeySchema: [
    {
      AttributeName: 'token',
      KeyType: 'HASH'
    }
  ],
  AttributeDefinitions: [{
    AttributeName: 'token',
    AttributeType: 'S'
  }],
  ProvisionedThroughput: { // required provisioned throughput for the table
    ReadCapacityUnits: 1,
    WriteCapacityUnits: 1
  }
};

var params = {
  TableName: tableName,
  Item: {
    token: {S: 'token'},
    expires: {S: expires.toISOString()},
    userUuid: {S: '1234'}
  },
  ReturnValues: 'NONE',
  ReturnConsumedCapacity: "NONE",
  ReturnItemCollectionMetrics: "NONE"
};

dbClient.createTable(ctParams, function (err, d) {
  if (!err) {
    dbClient.putItem(params, function (err, d) {
      if (err) {
        console.log("putItem error", err);
      }
      else {
        console.log("SUCCESS");
      }
    });
  }
  else {
    console.log("createTable error", err);
  }
});

```

How can I pull off the 2 different clients co-existing?

**Comment by raymolin** [comment]
The mutation of the low level client is by design.  If you pass in a client to the document-level wrapper, it appends request/response handlers to that instance of the DynamoDB client.  That being said, what you would want to do instead is create two separate instances of the client. 

Generally speaking, you can usually just make the necessary configuration updates in the AWS.config object, like so
```javascript

AWS.config.update({region, credentials, ...})
client = new AWS.DynamoDB();
docClient = new DOC.DynamoDB();
```

However, in your case because you want to specify the endpoint (to point at DynamoDBLocal), you'll have to create two instances of the AWS client and pass one of them into the DOC client.

```javascript

client = new AWS.DynamoDB({<endpoint>});
docClient = new DOC.DynamoDB(new AWS.DynamoDB({<endpoint>}));
```

**Comment by doapp-ryanp** [comment]
Ah ok thanks.  I'll test this out here over the next few days and then close the issue if it does indeed resolve. Thanks for the prompt reply.

**Comment by raymolin** [comment]
Please re-open if you have any other issue. Thanks!
