### ISSUE TITLE
Please Improve the documentation coverage

### ISSUE THREAD

**Issue by tchiagoneses** [awslabs/dynamodb-document-js-sdk#39]
I had a little trouble to figure this out:

var params = {};

params.TableName = "myTable";

params.FilterExpression = "#v = :cp value";
params.Expression AttributeNames = {"#v" : "DataCompraTempo"};
params.ExpressionAttributeValues = {":cpvalue" : 'someValue'};

docClient.scan(params, pfunc);

Why isn't the 'scan' operation, as well as the other known operations, explicitly documented here, on the SDK page?

**Comment by raymolin** [comment]
Anything specific you had trouble figuring out?  This library is a wrapper on top of the general [AWS JS SDK](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html), but you can also use the general [DynamoDB Operations API Reference](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Operations.html) if you would like.

**Comment by amcp** [comment]
You can find usage examples [here](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/document_client.js#L321).
