### ISSUE TITLE
ADD value to set seems not possible

### ISSUE THREAD

**Issue by SamVerschueren** [awslabs/dynamodb-document-js-sdk#40]
Hi, I try to add a value to a string set (SS) in my table. This is the request I use.

```json
{
    "TableName": "User",
    "Key": {
        "name": "sam"
    },
    "UpdateExpression": "ADD #k_token :v_token",
    "ExpressionAttributeNames": {
        "#k_token": "token"
    },
    "ExpressionAttributeValues": {
        ":v_token": ["newToken"]
    }
}
```

This is the error I receive

```
Invalid UpdateExpression: Incorrect operand type for operator or function; operator: ADD, operand type: LIST
```

This seems kinda logical because an array is parsed automatically to a list. So I tried it with using `docClient.Set(values, 'S')` to create a string set but then I receive the following error. It seems like he wants to store the entire object as is instead of the set.

```
An operand in the update expression has an incorrect data type
```

**Comment by raymolin** [comment]
Can you confirm that the values in your list "values" for the docClient.SET is of the correct String data types?  I've run this command and it works for me 


    params = {};
    params.TableName = "TestTable";
    params.Key = {Key : "myKey"};
    params.UpdateExpression = "ADD StrSet :value";
    params.ExpressionAttributeValues = {":value": db.Set(["str1", "anotherStr"], 'S')};
    db.updateItem(params);

**Comment by SamVerschueren** [comment]
Hi @raymolin 

I checked it and it was my bad. The original value I tried to add values to was a list and not a set. That's why the method returned errors.

**Comment by az-ericso** [comment]
```js
"UpdateExpression" : "SET employeeID = list_append(<<table_name>>, :val)",
```
Works for us

**Comment by rubab** [comment]
I have tried following code but not working.
```
UpdateExpression: "Set #p = list_append(if_not_exists(#p, :empty_list), :pics)",
      // UpdateExpression: "ADD #p :pics",
      ExpressionAttributeNames: {
        "#p": "pics"
      },
      ExpressionAttributeValues: {
          ":pics": [{field1: "value1"}],
          ":empty_list": []
      },
```
I also tried following object for pics
```
{
            "L": [{
                "M": {
                    "field1": { "S": "value1"},
                    "field2": { "S": "value2"}
                }
            }]
        }
```
Please let know what I am doing wrong.

Thanks,

**Comment by chancyk** [comment]
@rubab Any luck?

I've run into the same problem trying to `list_append` to a field defined as these three variations:

transits: [ID!]
```
{
    "expression": "SET #t = list_append(if_not_exists(#t, :empty_list), :transit_id),
    "expressionNames": {
        "#t" : "transits"
    },
    "expressionValues": {
        ":transit_id": {
            "L": [{
                "S": "$input.transit_id"
            }]
        },
        ":empty_list": { "L" : [] }
    }
}
```
transits: [String!]
```
{
    "expression": "SET #t = list_append(if_not_exists(#t, :empty_list), :transit_id),
    "expressionNames": {
        "#t" : "transits"
    },
    "expressionValues": {
        ":transit_id": {
            "L": [{
                "S": "$input.transit_id"
            }]
        },
        ":empty_list": { "L" : [] }
    } 
}
```
type TransitID
{
    id: String!
}
transits: [TransitID!]
```
{
    "expression": "SET #t = list_append(if_not_exists(#t, :empty_list), :transit_id),
    "expressionNames": {
        "#t" : "transits"
    },
    "expressionValues": {
        ":transit_id": {
            "L": [{ "M": {
                    "id": {
                        "S": "$input.transit_id"
                    }
                }}]
            }
        },
        ":empty_list": { "L" : [] }
}
```

All of these fail with the same errors:

```
Invalid UpdateExpression: Incorrect operand type for operator or function;
operator or function: list_append, operand type: S
```

**Comment by KarmaBlackshaw** [comment]
any luck on that problem @chancyk ? It's been bugging me for two days now 😫

**Comment by chancyk** [comment]
@KarmaBlackshaw Sorry for the false hope notification, but I don't believe I ever solved it and just ended up coming up with some other solution. :(
