### ISSUE TITLE
Application Architecture Question

### ISSUE THREAD

**Issue by rickwaugh1** [awslabs/dynamodb-document-js-sdk#41]
Definitely need some more examples. Sorry for the long question, but I wanted to be very clear on what I'm trying to figure out.

We are using DynamoDB with node.js and Express to create REST APIs. We have started to go with Dynamo on the backend, for simplicity of operations. 

We have started to use  the DynamoDB Document SDK from AWS Labs to simplify usage, and make it easy to work with JSON documents. To instantiate a client to use, we need to do the following:

AWS = require('aws-sdk');
Doc = require("dynamodb-doc");
var Dynamodb = new AWS.DynamoDB();
var DocClient = new Doc.DynamoDB(Dynamodb);

My question is, where do those last two steps need to take place, in order to ensure data integrity? I’m concerned about an object that is waiting for something happen in Dynamo, being taken over by another process, and getting the data swapped, resulting in incorrect data being sent back to a client, or incorrect data being written to the database.

We have three parts to our REST API. We have the main server.js file, that starts express and the HTTP server, and assigns resources to it, sets up logging, etc. We do the first two steps of creating the connection to Dynamo, creating the AWS and Doc requires, at that point. Those vars are global in the app. We then, depending on the route being followed through the API, call a controller that parses up the input from the rest call. It then calls a model file, that does the interacting with Dynamo, and provides the response back to the controller, which formats the return package along with any errors, and sends it to the client. The model is simply a group of methods that essentially cover the same area of the app. We would have a user model, for instance, that covers things like login and account creation in an app.

I have done the last two steps above for creating the dynamo object in two places. One, I have simply placed them in one spot, at the top of each model file. I do not reinstantiate them in the methods below, I simply use them. I have also instantiated them within the methods, when we are preparing to the make the call to Dynamo, making them entirely local to the method, and pass them to a secondary function if needed. This second method has always struck me as the safest way to do it. However, under load testing, I have run into situations where we seem to have overwhelmed the outgoing network connections, and I start getting errors telling me that the DynamoDB end point is unavailable in the region I’m running in. I believe this is from the additional calls required to make the connections.

So, the question is, is creating those objects local to the model file, safe, or do they need to be created locally in the method that uses them? Any thoughts would be much appreciated.

**Comment by SamVerschueren** [comment]
I don't really thinks it matters where or how many objects you create. The JS library is essentially just an easier way for executing HTTP requests to Amazon. So if you create 1 object, or 1000 objects, it does not matter for the data being stored in DynamoDB as it is just a facade for the REST API of Amazon. The integrity is handled at the servers hosting DynamoDB.

But I guess you would receive a greater response on the Amazon forums.

**Comment by amcp** [comment]
If you are concerned about consistency when updating items (with any SDK), use conditional updates, optionally incrementing a version attribute
