### ISSUE TITLE
Potential bug with using updateItem method

### ISSUE THREAD

**Issue by keithchilders** [awslabs/dynamodb-document-js-sdk#44]
Sporadically and with no pattern that I can determine, I will receive validation errors from the dynamodb API when using this client to run updateexpressions. Here is an example of a document payload that has produced the error then successfully updated on a subsequent retry:

```
{ 
  TableName: 'stacks.dev', 
  Key:  { 
    region: 'us-west-2', 
    id: 'stack-hyperlynx-pi-876F19300672C3D265789552F1A0D910' 
  }, 
  UpdateExpression: 'set #resources.InstanceDNSName = :value', 
  ExpressionAttributeNames: { 
    '#resources': 'resources' 
  }, 
  ExpressionAttributeValues:  { 
    ':value':  { 
      type: 'AWS::Route53::RecordSet', 
      status: 'CREATE_IN_PROGRESS', 
      id: undefined, 
      reason: null 
    } 
  } 
}
```

This was passed into updateItem() twice within 10 seconds and the first attempt failed with this error:

{ [MultipleValidationErrors: There were 66 validation errors: \* InvalidParameterType: Expected params.Key['region'] to be a structure \* UnexpectedParameter: Unexpected key '0' found in params.Key['region'] \* UnexpectedParameter: Unexpected key '1' found in params.Key['region'] \* UnexpectedParameter: Unexpected key '2' found in params.Key['region'] \* UnexpectedParameter: Unexpected key '3' found in params.Key['region'] \* UnexpectedParameter: Unexpected key '4' found in params.Key['region'] \* UnexpectedParameter: Unexpected key '5' found in params.Key['region'] \* UnexpectedParameter: Unexpected key '6' found in params.Key['region'] \* UnexpectedParameter: Unexpected key '7' found in params.Key['region'] \* UnexpectedParameter: Unexpected key '8' found in params.Key['region'] \* InvalidParameterType: Expected params.Key['id'] to be a structure \* UnexpectedParameter: Unexpected key '0' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '1' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '2' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '3' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '4' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '5' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '6' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '7' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '8' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '9' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '10' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '11' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '12' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '13' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '14' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '15' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '16' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '17' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '18' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '19' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '20' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '21' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '22' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '23' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '24' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '25' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '26' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '27' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '28' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '29' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '30' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '31' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '32' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '33' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '34' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '35' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '36' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '37' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '38' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '39' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '40' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '41' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '42' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '43' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '44' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '45' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '46' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '47' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '48' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '49' found in params.Key['id'] \* UnexpectedParameter: Unexpected key '50' found in params.Key['id'] \* UnexpectedParameter: Unexpected key 'type' found in params.ExpressionAttributeValues[':value'] \* UnexpectedParameter: Unexpected key 'status' found in params.ExpressionAttributeValues[':value'] \* UnexpectedParameter: Unexpected key 'id' found in params.ExpressionAttributeValues[':value'] \* UnexpectedParameter: Unexpected key 'reason' found in params.ExpressionAttributeValues[':value']] message: 'There were 66 validation errors:\n\* InvalidParameterType: Expected params.Key[\'region\'] to be a structure\n\* UnexpectedParameter: Unexpected key \'0\' found in params.Key[\'region\']\n\* UnexpectedParameter: Unexpected key \'1\' found in params.Key[\'region\']\n\* UnexpectedParameter: Unexpected key \'2\' found in params.Key[\'region\']\n\* UnexpectedParameter: Unexpected key \'3\' found in params.Key[\'region\']\n\* UnexpectedParameter: Unexpected key \'4\' found in params.Key[\'region\']\n\* UnexpectedParameter: Unexpected key \'5\' found in params.Key[\'region\']\n\* UnexpectedParameter: Unexpected key \'6\' found in params.Key[\'region\']\n\* UnexpectedParameter: Unexpected key \'7\' found in params.Key[\'region\']\n\* UnexpectedParameter: Unexpected key \'8\' found in params.Key[\'region\']\n\* InvalidParameterType: Expected params.Key[\'id\'] to be a structure\n\* UnexpectedParameter: Unexpected key \'0\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'1\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'2\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'3\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'4\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'5\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'6\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'7\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'8\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'9\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'10\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'11\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'12\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'13\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'14\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'15\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'16\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'17\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'18\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'19\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'20\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'21\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'22\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'23\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'24\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'25\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'26\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'27\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'28\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'29\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'30\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'31\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'32\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'33\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'34\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'35\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'36\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'37\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'38\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'39\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'40\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'41\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'42\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'43\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'44\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'45\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'46\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'47\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'48\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'49\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'50\' found in params.Key[\'id\']\n\* UnexpectedParameter: Unexpected key \'type\' found in params.ExpressionAttributeValues[\':value\']\n\* UnexpectedParameter: Unexpected key \'status\' found in params.ExpressionAttributeValues[\':value\']\n\* UnexpectedParameter: Unexpected key \'id\' found in params.ExpressionAttributeValues[\':value\']\n\* UnexpectedParameter: Unexpected key \'reason\' found in params.ExpressionAttributeValues[\':value\']', code: 'MultipleValidationErrors', time: Wed Aug 26 2015 15:53:30 GMT+0000 (UTC), errors: [Object], originalError: [Object] } }

The second attempt succeeded. It appears that the client is not wrapping the Key attributes or the ExpressionAttributeValues in the appropriate dynamodb wire types, but only sometimes? I'm also not sure why it would be splitting strings into arrays and sending each character as a separate index?

**Comment by keithchilders** [comment]
This might be related to the undefined value in the ExpressionAttributeValues map. I made that a null and haven't seen the issue again (yet). Will update if I see it again.

**Comment by SamVerschueren** [comment]
Have seen this as well, definitely the `undefined` value.

**Comment by readworks** [comment]
The best fix is to upgrade to the latest AWS Javascript SDK (2.2.x+), where undefined is treated as one would expect (just as None is treated in boto3 client).

**Comment by supermikol** [comment]
Just spent an hour trying to figure out what was causing the error, and indeed it was the undefined. A better error notification would've been nice.

**Comment by amcp** [comment]
Seems like you found resolution. Please use the AWS SDK for JS as it includes the DocumentClient.
