### ISSUE TITLE
attribute_exists does not like - (dash)

### ISSUE THREAD

**Issue by XiSmartElf** [awslabs/dynamodb-document-js-sdk#50]
attribute_exists dynamodb does not like dash so if i do  attribute_exist(movie.movieId) where movieId is a guid like dsda-dasfsd-gfdhgfh-fsdfs it will fail the validation. I had to do dasdfd_dasfds_dsfsd_ds or something like that. Is there anyway i can use expressionattributename or value fr attribute_exist?

**Comment by amcp** [comment]
attribute_exists only accepts document paths for the first argument. If the paths are not canonical (for example, include dashes), you can use the AttributeExpressionNames argument to define a placeholder for those parts of the path.

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.AccessingItemAttributes.html#DocumentPaths

2016/03/14 8:18、Xi He <notifications@github.com<mailto:notifications@github.com>> のメッセ`ジ:


attribute_exists dynamodb does not like dash so if i do attribute_exist(movie.movieId) where movieId is a guid like dsda-dasfsd-gfdhgfh-fsdfs it will fail the validation. I had to do dasdfd_dasfds_dsfsd_ds or something like that. Is there anyway i can use expressionattributename or value fr attribute_exist?

―

**Comment by XiSmartElf** [comment]
what's the diff btn expressionattributename  and AttributeExpressionNames ? i tried expressionattributename   but doesn't work for path as i said in my post.
