### ISSUE TITLE
"Optimistic Locking With Version Number" support for dynamodb

### ISSUE THREAD

**Issue by jasonfill** [awslabs/dynamodb-document-js-sdk#51]
Having this feature included in the nodejs sdk would be helpful.

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.OptimisticLocking.html

**Comment by ngothanhtai** [comment]
+1

**Comment by swhobbit** [comment]
+1

**Comment by MinsterMind** [comment]
+1

**Comment by tludmetal** [comment]
+1. Very important feature.

**Comment by beeva-manueldepaz** [comment]
+1

**Comment by mllanes** [comment]
+1

**Comment by leggiero** [comment]
+1

**Comment by amcp** [comment]
You can use the Document client in the [AWS SDK for JS with a conditional update](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/document_client.js#L321) to achieve optimistic locking with version numbers.

**Comment by Keegomyneego** [comment]
@amcp to clarify, the `version` attribute isn't anything special or provided by Dynamo correct? It's just another attribute an AWS SDK consumer would put into their table for the purpose of manually checking via an update expression and incrementing when finished?

i.e.
```javascript
// get Employee with employeeId 123, assume it looks like: {
//   employeeId: '123',
//   name: 'Robert',
//   version: 1
// }

var currentVersion = employee.version // version of above object 

var params = {
    TableName: 'Employee',
    Key: {
        employeeId: '123'
    },
    UpdateExpression: 'set #name = :newName, #version = :newVersion',
    ConditionExpression: '#version = :expectedVersion',
    ExpressionAttributeNames: {
        '#name': 'name',
        '#version': 'version'
    },
    ExpressionAttributeValues: {
        ':newName': 'Bob',
        ':newVersion': currentVersion + 1,
        ':expectedVersion': currentVersion
    }
}

var documentClient = new AWS.DynamoDB.DocumentClient();

documentClient.update(params, function(err, data) {
    if (err) console.log(err);
    else console.log(data);
});
```

**Comment by amcp** [comment]
@Keegomyneego Correct, its just another attribute.

**Comment by odupuy** [comment]
[Documentation and some examples](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html)
