### ISSUE TITLE
publish to bower.io

### ISSUE THREAD

**Issue by modellurgist** [awslabs/dynamodb-document-js-sdk#9]
Please consider providing this lib there via http://bower.io/docs/creating-packages/#register

I see its `aws-sdk-js` dependency is already there:  http://bower.io/search/?q=aws-sdk

**Comment by namel** [comment]
Would be great to have this

**Comment by amcp** [comment]
The DynamoDB [DocumentClient is already in the AWS SDK for JS](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/document_client.js#L321). Closing.
